import { TelemetryKPIs, TestScenario, TransactionItem } from "./types";

export const TEST_SCENARIOS: TestScenario[] = [
  {
    id: "sbi_cbs_downtime",
    label: "SBI UPI AutoPay — Bank Server Down (₹149 Swiggy One)",
    tier: "Pro",
    amount: 149.0,
    code: "bank_server_down",
    bank: "SBI",
    description: "2:00 AM CBS batch maintenance failure. Shifting to 10:00 AM daytime via Cashfree yields massive +78.9% success lift.",
  },
  {
    id: "zomato_payday_funds",
    label: "HDFC Bank — Insufficient Funds (₹999 Zomato Gold)",
    tier: "Enterprise",
    amount: 999.0,
    code: "insufficient_funds",
    bank: "HDFC Bank",
    description: "Salaried debit liquidity decline. Synchronizes with 1st of month Indian payroll disbursement window.",
  },
  {
    id: "upi_mandate_revoked",
    label: "PhonePe — Mandate Revoked (₹89 JioCinema Family)",
    tier: "Starter",
    amount: 89.0,
    code: "upi_mandate_revoked",
    bank: "PhonePe",
    description: "Hard decline. Customer revoked mandate in UPI app. Circuit breaker forces P=0.0 to prevent NPCI penalties.",
  },
  {
    id: "rbi_afa_limit",
    label: "ICICI Bank — RBI AFA Limit Exceeded (₹18,500 Annual)",
    tier: "Enterprise",
    amount: 18500.0,
    code: "rbi_afa_limit_exceeded",
    bank: "ICICI Bank",
    description: "RBI circular violation (> ₹15,000 without OTP). Permanently unrecoverable without step-up OTP.",
  },
  {
    id: "zerodha_streak_retry",
    label: "Axis Bank — Zerodha Streak Sub (₹690 Streak)",
    tier: "Growth",
    amount: 690.0,
    code: "do_not_honor",
    bank: "Axis Bank",
    description: "3DS risk block. Successfully re-routed through Razorpay direct acquiring switch during business hours.",
  },
];

export const INITIAL_KPIS: TelemetryKPIs = {
  interceptedWebhooks: 14892,
  webhookRatePerSec: 42.8,
  protectedMRR: 284920,
  recoveredAccounts: 1842,
  meanRecoveryDelta: 33.5,
  sparklineHistory: [
    { value: 21.2 },
    { value: 22.8 },
    { value: 24.1 },
    { value: 23.5 },
    { value: 26.4 },
    { value: 25.8 },
    { value: 28.1 },
    { value: 29.5 },
    { value: 27.9 },
    { value: 30.2 },
    { value: 31.8 },
    { value: 32.4 },
    { value: 31.1 },
    { value: 33.5 },
  ],
  gateways: [
    { name: "Razorpay", latencyMs: 22, loadPct: 42, status: "optimal", fee: 2.0 },
    { name: "Cashfree", latencyMs: 16, loadPct: 34, status: "optimal", fee: 1.2 },
    { name: "PayU", latencyMs: 25, loadPct: 15, status: "healthy", fee: 1.8 },
    { name: "BillDesk", latencyMs: 38, loadPct: 9, status: "healthy", fee: 2.5 },
  ],
};

export const INITIAL_TRANSACTIONS: TransactionItem[] = [
  {
    id: "txn_9f81a0e2",
    timestamp: "2 mins ago",
    customerEmail: "sarah.chen@hyperscale.io",
    subscriptionTier: "Enterprise",
    invoiceAmount: 499.0,
    declineCode: "do_not_honor",
    declineCategory: "soft_authorization",
    issuingBank: "Bank of America",
    cardNetwork: "visa",
    cardType: "credit",
    binCountry: "US",
    status: "rescheduled",
    routingAction: "daytime_failover_scheduler",
    currentGateway: "stripe",
    targetGateway: "adyen",
    targetTime: "2026-09-19T14:00:00Z",
    targetTimeFormatted: "Sat 10:00 AM EDT",
    retryAttempt: 1,
    successProbability: 0.428,
    baselineProbability: 0.115,
    recoveryLift: 0.313,
    expectedValue: 212.99,
    gatewayAuthFee: 0.12,
    fatigueCost: 0.5,
    isTerminal: false,
    shapExplanation: {
      baseValue: -0.84,
      predictionMargin: 0.72,
      topPositiveFeatures: [
        {
          feature: "current_gateway (Adyen)",
          value: "adyen",
          formattedAttribution: "+24.5%",
          attributionPct: 24.5,
        },
        {
          feature: "customer_active_daytime",
          value: 10,
          formattedAttribution: "+18.2%",
          attributionPct: 18.2,
        },
        {
          feature: "card_network_visa",
          value: "visa",
          formattedAttribution: "+8.1%",
          attributionPct: 8.1,
        },
      ],
      topNegativeFeatures: [
        {
          feature: "invoice_amount_usd",
          value: 499.0,
          formattedAttribution: "-7.4%",
          attributionPct: -7.4,
        },
        {
          feature: "historical_issuer_friction",
          value: "Bank of America",
          formattedAttribution: "-4.2%",
          attributionPct: -4.2,
        },
      ],
      rationale:
        "Shifted retry to Saturday 10:00 AM via Adyen: Capitalizes on active daytime customer hours for 3DS verification (+18.2% attribution) while routing around Stripe issuer-declines for US credit cards (+24.5% attribution).",
    },
    circuitBreaker: null,
  },
  {
    id: "txn_3b7c91d4",
    timestamp: "4 mins ago",
    customerEmail: "alex.m@fintechflow.co",
    subscriptionTier: "Pro",
    invoiceAmount: 149.0,
    declineCode: "insufficient_funds",
    declineCategory: "soft_liquidity",
    issuingBank: "Chase",
    cardNetwork: "visa",
    cardType: "debit",
    binCountry: "US",
    status: "rescheduled",
    routingAction: "payroll_balance_scheduler",
    currentGateway: "stripe",
    targetGateway: "adyen",
    targetTime: "2026-09-20T08:00:00Z",
    targetTimeFormatted: "Sun 04:00 AM EDT",
    retryAttempt: 1,
    successProbability: 0.524,
    baselineProbability: 0.082,
    recoveryLift: 0.442,
    expectedValue: 77.46,
    gatewayAuthFee: 0.12,
    fatigueCost: 0.5,
    isTerminal: false,
    shapExplanation: {
      baseValue: -0.84,
      predictionMargin: 1.12,
      topPositiveFeatures: [
        {
          feature: "is_banking_settlement_window",
          value: 1,
          formattedAttribution: "+32.1%",
          attributionPct: 32.1,
        },
        {
          feature: "is_payday_proximity",
          value: 1,
          formattedAttribution: "+24.8%",
          attributionPct: 24.8,
        },
        {
          feature: "current_gateway (Adyen)",
          value: "adyen",
          formattedAttribution: "+11.4%",
          attributionPct: 11.4,
        },
      ],
      topNegativeFeatures: [
        {
          feature: "retry_attempt_number",
          value: 1,
          formattedAttribution: "-3.1%",
          attributionPct: -3.1,
        },
      ],
      rationale:
        "Shifted retry to Sunday 04:00 AM via Adyen: Capitalizes on bi-weekly payroll balance replenishment (+24.8% attribution) and overnight Fedwire/ACH settlement clearance (+32.1% attribution) for US debit cards.",
    },
    circuitBreaker: null,
  },
  {
    id: "txn_7a2e4f09",
    timestamp: "7 mins ago",
    customerEmail: "marcus.v@darktrace-shield.net",
    subscriptionTier: "Growth",
    invoiceAmount: 99.0,
    declineCode: "stolen_card",
    declineCategory: "hard_decline",
    issuingBank: "Wells Fargo",
    cardNetwork: "mastercard",
    cardType: "credit",
    binCountry: "US",
    status: "circuit_tripped",
    routingAction: "customer_self_serve_dunning",
    currentGateway: "stripe",
    targetGateway: "NONE (Blocked)",
    targetTime: "N/A",
    targetTimeFormatted: "Direct Self-Serve",
    retryAttempt: 1,
    successProbability: 0.0,
    baselineProbability: 0.0,
    recoveryLift: 0.0,
    expectedValue: 0.0,
    gatewayAuthFee: 0.0,
    fatigueCost: 0.0,
    isTerminal: true,
    shapExplanation: null,
    circuitBreaker: {
      isUnrecoverable: true,
      routingAction: "customer_self_serve_dunning",
      reason:
        "Hard decline: Card reported stolen. Retrying triggers severe card brand network fines ($15-$25/retry).",
      suggestedAction:
        "Do not retry. Route immediately to customer self-serve dunning to prevent network penalties and auth fees.",
    },
  },
  {
    id: "txn_1c8e62b0",
    timestamp: "11 mins ago",
    customerEmail: "devops-admin@cloudpilot.co.uk",
    subscriptionTier: "Enterprise",
    invoiceAmount: 299.0,
    declineCode: "insufficient_funds",
    declineCategory: "soft_liquidity",
    issuingBank: "Barclays",
    cardNetwork: "visa",
    cardType: "debit",
    binCountry: "GB",
    status: "rescheduled",
    routingAction: "payroll_balance_scheduler",
    currentGateway: "stripe",
    targetGateway: "adyen",
    targetTime: "2026-09-20T04:00:00Z",
    targetTimeFormatted: "Sun 05:00 AM BST",
    retryAttempt: 2,
    successProbability: 0.468,
    baselineProbability: 0.124,
    recoveryLift: 0.344,
    expectedValue: 138.66,
    gatewayAuthFee: 0.12,
    fatigueCost: 1.25,
    isTerminal: false,
    shapExplanation: {
      baseValue: -0.84,
      predictionMargin: 0.88,
      topPositiveFeatures: [
        {
          feature: "is_banking_settlement_window",
          value: 1,
          formattedAttribution: "+30.4%",
          attributionPct: 30.4,
        },
        {
          feature: "bin_country_uk_adyen_affinity",
          value: "GB",
          formattedAttribution: "+16.8%",
          attributionPct: 16.8,
        },
      ],
      topNegativeFeatures: [
        {
          feature: "card_fatigue_attempt_2",
          value: 2,
          formattedAttribution: "-12.5%",
          attributionPct: -12.5,
        },
      ],
      rationale:
        "Shifted retry to Sunday 05:00 AM BST via Adyen: Capitalizes on BACS overnight clearing (+30.4% attribution) with local European acquiring while mitigating attempt #2 card fatigue decay.",
    },
    circuitBreaker: null,
  },
  {
    id: "txn_5e11d98a",
    timestamp: "14 mins ago",
    customerEmail: "todd.k@apipulse.dev",
    subscriptionTier: "Starter",
    invoiceAmount: 49.0,
    declineCode: "gateway_timeout",
    declineCategory: "soft_technical",
    issuingBank: "Citibank",
    cardNetwork: "mastercard",
    cardType: "credit",
    binCountry: "US",
    status: "rescheduled",
    routingAction: "short_interval_exponential_backoff",
    currentGateway: "stripe",
    targetGateway: "checkout_com",
    targetTime: "2026-09-18T16:55:00Z",
    targetTimeFormatted: "+15m Exponential Backoff",
    retryAttempt: 1,
    successProbability: 0.824,
    baselineProbability: 0.412,
    recoveryLift: 0.412,
    expectedValue: 39.68,
    gatewayAuthFee: 0.2,
    fatigueCost: 0.5,
    isTerminal: false,
    shapExplanation: {
      baseValue: -0.84,
      predictionMargin: 1.65,
      topPositiveFeatures: [
        {
          feature: "elapsed_time_under_1h",
          value: "0.25h",
          formattedAttribution: "+44.1%",
          attributionPct: 44.1,
        },
        {
          feature: "gateway_failover",
          value: "checkout_com",
          formattedAttribution: "+15.2%",
          attributionPct: 15.2,
        },
      ],
      topNegativeFeatures: [
        {
          feature: "auth_fee_checkout_com",
          value: 0.2,
          formattedAttribution: "-2.1%",
          attributionPct: -2.1,
        },
      ],
      rationale:
        "Shifted retry to +15m via Checkout.com: Rapidly executes within high-probability transient network error window (>75% conversion) avoiding upstream gateway downtime.",
    },
    circuitBreaker: null,
  },
  {
    id: "txn_8c41bf39",
    timestamp: "19 mins ago",
    customerEmail: "vikram.r@paylogic.in",
    subscriptionTier: "Pro",
    invoiceAmount: 79.0,
    declineCode: "card_velocity_exceeded",
    declineCategory: "soft_liquidity",
    issuingBank: "HDFC Bank",
    cardNetwork: "rupay",
    cardType: "debit",
    binCountry: "IN",
    status: "rescheduled",
    routingAction: "payroll_balance_scheduler",
    currentGateway: "stripe",
    targetGateway: "adyen",
    targetTime: "2026-09-19T21:30:00Z",
    targetTimeFormatted: "Sun 03:00 AM IST",
    retryAttempt: 1,
    successProbability: 0.448,
    baselineProbability: 0.098,
    recoveryLift: 0.35,
    expectedValue: 34.77,
    gatewayAuthFee: 0.12,
    fatigueCost: 0.5,
    isTerminal: false,
    shapExplanation: {
      baseValue: -0.84,
      predictionMargin: 0.74,
      topPositiveFeatures: [
        {
          feature: "rolling_velocity_reset",
          value: "24h cooldown",
          formattedAttribution: "+38.4%",
          attributionPct: 38.4,
        },
        {
          feature: "interbank_neft_clearance",
          value: 1,
          formattedAttribution: "+19.2%",
          attributionPct: 19.2,
        },
      ],
      topNegativeFeatures: [
        {
          feature: "issuer_hdfc_risk_sensitivity",
          value: "high",
          formattedAttribution: "-11.8%",
          attributionPct: -11.8,
        },
      ],
      rationale:
        "Shifted retry to Sunday 03:00 AM IST via Adyen: Allows rolling daily issuer limit reset (+38.4% attribution) while buffering HDFC strict velocity risk checks.",
    },
    circuitBreaker: null,
  },
  {
    id: "txn_2d99ab41",
    timestamp: "24 mins ago",
    customerEmail: "fraud-alert@shieldguard.com",
    subscriptionTier: "Enterprise",
    invoiceAmount: 1200.0,
    declineCode: "fraudulent",
    declineCategory: "hard_decline",
    issuingBank: "Capital One",
    cardNetwork: "mastercard",
    cardType: "credit",
    binCountry: "US",
    status: "circuit_tripped",
    routingAction: "customer_self_serve_dunning",
    currentGateway: "braintree",
    targetGateway: "NONE (Blocked)",
    targetTime: "N/A",
    targetTimeFormatted: "Direct Self-Serve",
    retryAttempt: 1,
    successProbability: 0.0,
    baselineProbability: 0.0,
    recoveryLift: 0.0,
    expectedValue: 0.0,
    gatewayAuthFee: 0.0,
    fatigueCost: 0.0,
    isTerminal: true,
    shapExplanation: null,
    circuitBreaker: {
      isUnrecoverable: true,
      routingAction: "customer_self_serve_dunning",
      reason:
        "Hard decline: Confirmed fraud rule triggered by issuer. Attempting re-authorization invites card brand compliance audit.",
      suggestedAction:
        "Halt automated retries immediately. Route to customer verification portal.",
    },
  },
];

export function createScenarioTransaction(scenarioId: string): TransactionItem {
  const scenario = TEST_SCENARIOS.find((s) => s.id === scenarioId) || TEST_SCENARIOS[0];
  const randHash = Math.random().toString(16).substring(2, 10);
  const nowStr = "Just now";

  if (scenario.code === "stolen_card" || scenario.code === "fraudulent") {
    return {
      id: `txn_${randHash}`,
      timestamp: nowStr,
      customerEmail: `user.${randHash.substring(0, 4)}@enterprise-client.com`,
      subscriptionTier: scenario.tier,
      invoiceAmount: scenario.amount,
      declineCode: scenario.code,
      declineCategory: "hard_decline",
      issuingBank: scenario.bank,
      cardNetwork: "visa",
      cardType: "credit",
      binCountry: "US",
      status: "circuit_tripped",
      routingAction: "customer_self_serve_dunning",
      currentGateway: "stripe",
      targetGateway: "NONE (Blocked)",
      targetTime: "N/A",
      targetTimeFormatted: "Direct Self-Serve",
      retryAttempt: 1,
      successProbability: 0.0,
      baselineProbability: 0.0,
      recoveryLift: 0.0,
      expectedValue: 0.0,
      gatewayAuthFee: 0.0,
      fatigueCost: 0.0,
      isTerminal: true,
      shapExplanation: null,
      circuitBreaker: {
        isUnrecoverable: true,
        routingAction: "customer_self_serve_dunning",
        reason: `Hard decline: ${scenario.code}. Bypassed ML inference to prevent card brand penalties.`,
        suggestedAction:
          "Halt retries immediately. Route directly to customer self-serve payment portal.",
      },
    };
  }

  // Soft decline simulation
  const isFunds = scenario.code === "insufficient_funds";
  const isTimeout = scenario.code === "gateway_timeout";
  const targetGateway = isFunds ? "adyen" : isTimeout ? "checkout_com" : "adyen";
  const targetFormatted = isTimeout ? "+15m Exponential Backoff" : "Sun 04:00 AM Local";
  const lift = isFunds ? 0.442 : 0.315;
  const pSuccess = isFunds ? 0.524 : 0.428;
  const ev = parseFloat((pSuccess * scenario.amount - 0.12 - 0.5).toFixed(2));

  return {
    id: `txn_${randHash}`,
    timestamp: nowStr,
    customerEmail: `billing.${randHash.substring(0, 4)}@saasgrowth.io`,
    subscriptionTier: scenario.tier,
    invoiceAmount: scenario.amount,
    declineCode: scenario.code,
    declineCategory: isFunds ? "soft_liquidity" : isTimeout ? "soft_technical" : "soft_authorization",
    issuingBank: scenario.bank,
    cardNetwork: "visa",
    cardType: isFunds ? "debit" : "credit",
    binCountry: "US",
    status: "rescheduled",
    routingAction: isFunds ? "payroll_balance_scheduler" : isTimeout ? "short_interval_exponential_backoff" : "daytime_failover_scheduler",
    currentGateway: "stripe",
    targetGateway: targetGateway,
    targetTime: new Date(Date.now() + 3600 * 28 * 1000).toISOString(),
    targetTimeFormatted: targetFormatted,
    retryAttempt: 1,
    successProbability: pSuccess,
    baselineProbability: parseFloat((pSuccess - lift).toFixed(3)),
    recoveryLift: lift,
    expectedValue: ev,
    gatewayAuthFee: 0.12,
    fatigueCost: 0.5,
    isTerminal: false,
    shapExplanation: {
      baseValue: -0.84,
      predictionMargin: 0.94,
      topPositiveFeatures: [
        {
          feature: isFunds ? "is_banking_settlement_window" : "elapsed_time_under_1h",
          value: 1,
          formattedAttribution: isFunds ? "+32.1%" : "+41.5%",
          attributionPct: isFunds ? 32.1 : 41.5,
        },
        {
          feature: isFunds ? "is_payday_proximity" : "gateway_failover",
          value: 1,
          formattedAttribution: isFunds ? "+24.8%" : "+18.2%",
          attributionPct: isFunds ? 24.8 : 18.2,
        },
      ],
      topNegativeFeatures: [
        {
          feature: "retry_attempt_number",
          value: 1,
          formattedAttribution: "-3.5%",
          attributionPct: -3.5,
        },
      ],
      rationale: isFunds
        ? `Shifted retry to ${targetFormatted} via ${targetGateway.toUpperCase()}: Capitalizes on bi-weekly payroll balance replenishment (+24.8%) and overnight settlement clearance (+32.1%).`
        : `Routed to ${targetGateway.toUpperCase()} during low-latency window (+41.5% attribution) avoiding upstream issuer blockage.`,
    },
    circuitBreaker: null,
  };
}

